/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#9f403d",
        "on-surface": "#2d3435",
        "on-tertiary": "#faf8f8",
        "tertiary-dim": "#535353",
        "on-background": "#2d3435",
        "on-primary": "#faf7f6",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-secondary-container": "#525252",
        "outline": "#757c7d",
        "on-tertiary-fixed": "#494a4a",
        "surface-variant": "#dde4e5",
        "secondary-fixed-dim": "#d6d4d3",
        "tertiary-fixed-dim": "#e6e5e5",
        "secondary": "#5f5f5f",
        "on-surface-variant": "#5a6061",
        "on-secondary-fixed-variant": "#5c5b5b",
        "primary-fixed": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container-highest": "#dde4e5",
        "primary-dim": "#535252",
        "background": "#f9f9f9",
        "inverse-on-surface": "#9c9d9d",
        "inverse-primary": "#ffffff",
        "primary-container": "#e5e2e1",
        "surface-container-low": "#f2f4f4",
        "tertiary-container": "#f5f3f3",
        "on-secondary-fixed": "#3f3f3f",
        "on-primary-container": "#525151",
        "on-primary-fixed": "#403f3f",
        "on-secondary": "#fbf8f8",
        "secondary-dim": "#535353",
        "on-tertiary-fixed-variant": "#666666",
        "inverse-surface": "#0c0f0f",
        "surface-bright": "#f9f9f9",
        "on-tertiary-container": "#5b5c5c",
        "tertiary-fixed": "#f5f3f3",
        "primary-fixed-dim": "#d6d4d3",
        "primary": "#5f5e5e",
        "surface-tint": "#5f5e5e",
        "surface-dim": "#d4dbdd",
        "secondary-fixed": "#e4e2e1",
        "on-error-container": "#752121",
        "on-error": "#fff7f6",
        "surface-container-high": "#e4e9ea",
        "outline-variant": "#adb3b4",
        "surface-container": "#ebeeef",
        "error-dim": "#4e0309",
        "secondary-container": "#e4e2e1",
        "error-container": "#fe8983",
        "tertiary": "#5f5f5f"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "2xl": "1rem",
      },
    },
  },
  plugins: [],
}
